INSERT INTO AER_AEROLINEA
                (
                    ARL_CODIGO_AEROLINEA,
                    ARL_NOMBRE,
                    ARL_PAIS_ORIGEN,
                    ARL_CODIGO_IATA,
                    ARL_CODIGO_ICAO,
                    ARL_ESTADO,
                    ARL_TELEFONO,
                    ARL_EMAIL,
                    ARL_SITIO_WEB
                )
                VALUES
                (
                    :codigo,
                    :nombre,
                    :paisOrigen,
                    :codigoIata,
                    :codigoIcao,
                    :estado,
                    :telefono,
                    :email,
                    :sitioWeb
                )
