INSERT INTO AER_MODELOAVION
                (
                    MOD_NOMBRE_MODELO,
                    MOD_FABRICANTE,
                    MOD_CAPACIDAD_PASAJEROS,
                    MOD_CAPACIDAD_CARGA,
                    MOD_ALCANCE_KM,
                    MOD_VELOCIDAD_CRUCERO,
                    MOD_ANIO_INTRODUCCION,
                    MOD_TIPO_MOTOR
                )
                VALUES
                (
                    :nombreModelo,
                    :fabricante,
                    :capacidadPasajeros,
                    :capacidadCarga,
                    :alcanceKm,
                    :velocidadCrucero,
                    :anioIntroduccion,
                    :tipoMotor
                )
