INSERT INTO AER_MANTENIMIENTOAVION
                (
                    MAN_ID_AVION,
                    MAN_TIPO_MANTENIMIENTO,
                    MAN_FECHA_INICIO,
                    MAN_FECHA_FIN_ESTIMADA,
                    MAN_FECHA_FIN_REAL,
                    MAN_DESCRIPCION_TRABAJO,
                    MAN_ID_EMPLEADO_RESPONSABLE,
                    MAN_COSTO_MANO_OBRA,
                    MAN_COSTO_REPUESTOS,
                    MAN_COSTO_TOTAL,
                    MAN_ESTADO
                )
                VALUES
                (
                    :idAvion,
                    :tipoMantenimiento,
                    :fechaInicio,
                    :fechaFinEstimada,
                    :fechaFinReal,
                    :descripcionTrabajo,
                    :idEmpleadoResponsable,
                    :costoManoObra,
                    :costoRepuestos,
                    :costoTotal,
                    :estado
                )
