INSERT INTO AER_LICENCIAEMPLEADO
                (
                    LIC_ID_EMPLEADO,
                    LIC_TIPO_LICENCIA,
                    LIC_NUMERO_LICENCIA,
                    LIC_FECHA_EMISION,
                    LIC_FECHA_VENCIMIENTO,
                    LIC_AUTORIDAD_EMISORA,
                    LIC_ESTADO
                )
                VALUES
                (
                    :idEmpleado,
                    :tipoLicencia,
                    :numeroLicencia,
                    :fechaEmision,
                    :fechaVencimiento,
                    :autoridadEmisora,
                    :estado
                )
