INSERT INTO AER_EMPLEADO
                (
                    EMP_NUMERO_EMPLEADO,
                    EMP_NOMBRES,
                    EMP_APELLIDOS,
                    EMP_FECHA_NACIMIENTO,
                    EMP_DPI,
                    EMP_NIT,
                    EMP_DIRECCION,
                    EMP_TELEFONO,
                    EMP_EMAIL,
                    EMP_FECHA_CONTRATACION,
                    EMP_ID_PUESTO,
                    EMP_ID_DEPARTAMENTO,
                    EMP_SALARIO_ACTUAL,
                    EMP_TIPO_CONTRATO,
                    EMP_ESTADO
                )
                VALUES
                (
                    :numeroEmpleado,
                    :nombres,
                    :apellidos,
                    :fechaNacimiento,
                    :dpi,
                    :nit,
                    :direccion,
                    :telefono,
                    :email,
                    :fechaContratacion,
                    :idPuesto,
                    :idDepartamento,
                    :salarioActual,
                    :tipoContrato,
                    :estado
                )
