INSERT INTO AER_AEROPUERTO
                (
                    AER_CODIGO_AEROPUERTO,
                    AER_NOMBRE,
                    AER_CIUDAD,
                    AER_PAIS,
                    AER_ZONA_HORARIA,
                    AER_ESTADO,
                    AER_TIPO,
                    AER_LATITUD,
                    AER_LONGITUD,
                    AER_CODIGO_IATA,
                    AER_CODIGO_ICAO
                )
                VALUES
                (
                    :codigoAeropuerto,
                    :nombre,
                    :ciudad,
                    :pais,
                    :zonaHoraria,
                    :estado,
                    :tipo,
                    :latitud,
                    :longitud,
                    :codigoIata,
                    :codigoIcao
                )
