export const modules = [
  { name: "Aerolineas", route: "Aerolinea", icon: "AL" },
  { name: "Aeropuertos", route: "Aeropuerto", icon: "AP" },
  { name: "Arrestos", route: "Arresto", icon: "AR" },
  { name: "Asignacion hangar", route: "AsignacionHangar", icon: "AH" },
  { name: "Asistencia", route: "Asistencia", icon: "AS" },
  { name: "Auditoria", route: "Auditoria", icon: "AU" },
  { name: "Aviones", route: "Avion", icon: "AV" },
  { name: "Busqueda vuelo", route: "BusquedaVuelo", icon: "BV" },
  { name: "Carrito compras", route: "CarritoCompra", icon: "CC" },
  { name: "Categorias repuesto", route: "CategoriaRepuesto", icon: "CR" },
  { name: "Clicks destino", route: "ClickDestino", icon: "CD" },
  { name: "Departamentos", route: "Departamento", icon: "DP" },
  { name: "Detalle orden compra", route: "DetalleOrdenCompra", icon: "DO" },
  { name: "Detalle venta boleto", route: "DetalleVentaBoleto", icon: "DV" },
  { name: "Dias vuelo", route: "DiasVuelo", icon: "DI" },
  { name: "Empleados", route: "Empleado", icon: "EM" },
  { name: "Escalas tecnicas", route: "EscalaTecnica", icon: "ET" },
  { name: "Hangares", route: "Hangar", icon: "HG" },
  { name: "Items carrito", route: "ItemCarrito", icon: "IC" },
  { name: "Licencias empleado", route: "LicenciaEmpleado", icon: "LE" },
  { name: "Mantenimientos avion", route: "MantenimientoAvion", icon: "MA" },
  { name: "Metodos pago", route: "MetodoPago", icon: "MP" },
  { name: "Modelos avion", route: "ModeloAvion", icon: "MO" },
  { name: "Movimientos repuesto", route: "MovimientoRepuesto", icon: "MR" },
  { name: "Objetos perdidos", route: "ObjetoPerdido", icon: "OP" },
  { name: "Ordenes compra repuesto", route: "OrdenCompraRepuesto", icon: "OC" },
  { name: "Pasajeros", route: "Pasajero", icon: "PA" },
  { name: "Planillas", route: "Planilla", icon: "PL" },
  { name: "Preferencias cliente", route: "PreferenciaCliente", icon: "PC" },
  { name: "Programas vuelo", route: "ProgramaVuelo", icon: "PV" },
  { name: "Promociones", route: "Promocion", icon: "PM" },
  { name: "Proveedores", route: "Proveedor", icon: "PR" },
  { name: "Puestos", route: "Puesto", icon: "PU" },
  { name: "Puntos venta", route: "PuntoVenta", icon: "PT" },
  { name: "Repuestos", route: "Repuesto", icon: "RP" },
  { name: "Repuestos utilizados", route: "RepuestoUtilizado", icon: "RU" },
  { name: "Reservas", route: "Reserva", icon: "RE" },
  { name: "Sesiones usuario", route: "SesionUsuario", icon: "SU" },
  { name: "Transacciones pago", route: "TransaccionPago", icon: "TP" },
  { name: "Tripulaciones", route: "Tripulacion", icon: "TR" },
  { name: "Uso promociones", route: "UsoPromocion", icon: "UP" },
  { name: "Venta boletos", route: "VentaBoleto", icon: "VB" },
  { name: "Vuelos", route: "Vuelo", icon: "VU" }
];

export const sampleBodies = {
  AsignacionHangar: {
    idHangar: 1,
    idAvion: 1,
    fechaEntrada: "2026-04-22T08:00:00",
    fechaSalidaProgramada: "2026-04-23T08:00:00",
    fechaSalidaReal: null,
    motivo: "Mantenimiento preventivo",
    costoHora: 125,
    costoTotal: 3000,
    estado: "Activo"
  },
  Asistencia: {
    idEmpleado: 1,
    fecha: "2026-04-22",
    horaEntrada: "2026-04-22T08:00:00",
    horaSalida: "2026-04-22T17:00:00",
    horasTrabajadas: 8,
    tipo: "Regular",
    estado: "Presente"
  },
  Aerolinea: {
    nombre: "Aurora Air",
    codigoIata: "AA",
    codigoIcao: "AUR",
    paisOrigen: "Guatemala",
    estado: "Activa"
  }
};
